-- Demo tables
CREATE TABLE ADDITIONAL_TABLE_ONE (
    ID NUMBER(19) NOT NULL PRIMARY KEY,
    FIRST_FIELD VARCHAR(45) NOT NULL,
    SECOND_FIELD VARCHAR(45) NOT NULL,
    SAMPLE_FLOAT FLOAT(4) NOT NULL,
    TRUE_FALSE_FIELD VARCHAR(1) NOT NULL,
    CONSTRAINT TRUE_FALSE_CHECK CHECK(TRUE_FALSE_FIELD IN ('y', 'n'))
);

CREATE TABLE ADDITIONAL_TABLE_TWO (
    ID NUMBER(19) NOT NULL PRIMARY KEY,
    NO_MORE_THAN INTEGER NOT NULL,
    CONSTRAINT NO_MORE_THAN_CHECK CHECK(NO_MORE_THAN <= 50) 
);

CREATE TABLE ADDITIONAL_TABLE_THREE (
    ID NUMBER(19) NOT NULL PRIMARY KEY,
    FLOATING NUMBER(3, 5) NOT NULL
);

-- Demo insertions
INSERT INTO ADDITIONAL_TABLE_ONE(ID, FIRST_FIELD, SECOND_FIELD, SAMPLE_FLOAT, TRUE_FALSE_FIELD) VALUES(1, 'Test one', 'Test two', 34.00, 'y');
INSERT INTO ADDITIONAL_TABLE_TWO (ID, NO_MORE_THAN) VALUES(1, 30);
INSERT INTO ADDITIONAL_TABLE_THREE(ID, FLOATING) VALUES(1, 4.5);

SELECT * FROM ADDITIONAL_TABLE_ONE;
UPDATE ADDITIONAL_TABLE_ONE SET FIRST_FIELD = 'Test one one' WHERE ID = 1;
SELECT * FROM ADDITIONAL_TABLE_ONE;

-- Constraint  updates
ALTER TABLE DEPARTMENT
ADD CONSTRAINT TITLE_CHECK CHECK(TITLE IN('Therapy', 'Pulmonology', 'Cardiology', 'Nefrology', 'Gastroenterology', 'Critical care', 
                                        'Chaplaincy', 'Diagnostic imaging', 'General surgery', 'Gynaecology', 'Haematology')) ENABLE NOVALIDATE;

-- Insertions
INSERT INTO CABINET(ID, ROOM_NUMBER, ROOM_TITLE, NUMBER_OF_PERS) VALUES(2, 336, 'Pulmonologist', '2');
INSERT INTO CABINET(ID, ROOM_NUMBER, ROOM_TITLE, NUMBER_OF_PERS) VALUES(3, 247, 'Dermatologist', 1);
INSERT INTO DOCTOR(ID, FIRST_NAME, LAST_NAME, AGE, POSITION, EXPERIENCE_YEARS, SPCLTY_ID, CAB_ID, DEP_ID) VALUES(1, 'John', 'Smith', 45, 'Physician', 20, 1, 1, 1);
INSERT INTO SPECIALITY(ID, SPEC_NAME, EXP_REQUIRED) VALUES(4, 'Pulmonologist', 5);
INSERT INTO DEPARTMENT(ID, TITLE, WORKERS_QUANTITY, NUMBER_OF_PATIENTS) VALUES(4, 'Nefrology', 45, 350);
INSERT INTO DEPARTMENT(ID, TITLE, WORKERS_QUANTITY, NUMBER_OF_PATIENTS) VALUES(5, 'Dermatology', 50, 450);
INSERT INTO DEPARTMENT(ID, TITLE, WORKERS_QUANTITY, NUMBER_OF_PATIENTS) VALUES(6, 'Therapy', 30, 400);
INSERT INTO DOCTOR(ID, FIRST_NAME, LAST_NAME, AGE, POSITION, EXPERIENCE_YEARS, SPCLTY_ID, CAB_ID, DEP_ID) VALUES(2, 'J�?nis', 'Bērziņ�?', 27, 'Pulmonologist', 4, 4, 2, 2);
INSERT INTO DOCTOR(ID, FIRST_NAME, LAST_NAME, AGE, POSITION, EXPERIENCE_YEARS, SPCLTY_ID, CAB_ID, DEP_ID) VALUES(3, 'Kaspars', 'Liepiņ�?', 42, 'Dermatologist', 21, 2, 3, 5);
INSERT INTO DOCTOR(ID, FIRST_NAME, LAST_NAME, AGE, POSITION, EXPERIENCE_YEARS, SPCLTY_ID, CAB_ID, DEP_ID) VALUES(4, 'Dainis', 'Zariņ�?', 35, 'Physician', 5, 1, 1, 5);
INSERT INTO DOCTOR(ID, FIRST_NAME, LAST_NAME, AGE, POSITION, EXPERIENCE_YEARS, SPCLTY_ID, CAB_ID, DEP_ID) VALUES(5, 'Jane', 'Cronfold', 29, 'Dermatologist', 5, 1, 1, 5);
commit;

SELECT * FROM DOCTOR WHERE ID = 1;
SELECT * FROM DOCTOR WHERE FIRST_NAME = 'Kaspars' AND EXPERIENCE_YEARS = 21;
SELECT * FROM DOCTOR;

SELECT 
    D.FIRST_NAME, 
    D.LAST_NAME, 
    D.POSITION, 
    D.EXPERIENCE_YEARS,
    SP.SPEC_NAME,
    SP.EXP_REQUIRED,
    C.ROOM_NUMBER,
    C.ROOM_TITLE,
    C.NUMBER_OF_PERS,
    DEP.TITLE,
    DEP.NUMBER_OF_PATIENTS
FROM DOCTOR D
    LEFT JOIN SPECIALITY SP ON D.SPCLTY_ID = SP.ID
    LEFT JOIN CABINET C ON D.CAB_ID = C.ID
    LEFT JOIN DEPARTMENT DEP ON D.DEP_ID = DEP.ID
offset 10 rows fetch next 2 rows only;
    
SELECT 
    D.FIRST_NAME, 
    D.LAST_NAME, 
    D.POSITION, 
    D.EXPERIENCE_YEARS,
    SP.SPEC_NAME,
    SP.EXP_REQUIRED,
    C.ROOM_NUMBER,
    C.ROOM_TITLE,
    C.NUMBER_OF_PERS,
    DEP.TITLE,
    DEP.NUMBER_OF_PATIENTS
FROM DOCTOR D
    JOIN SPECIALITY SP ON D.SPCLTY_ID = SP.ID
    JOIN CABINET C ON D.CAB_ID = C.ID
    JOIN DEPARTMENT DEP ON D.DEP_ID = DEP.ID;
    
SELECT 
    D.FIRST_NAME, 
    D.LAST_NAME, 
    D.POSITION, 
    D.EXPERIENCE_YEARS,
    SP.SPEC_NAME,
    SP.EXP_REQUIRED,
    C.ROOM_NUMBER,
    C.ROOM_TITLE,
    C.NUMBER_OF_PERS,
    DEP.TITLE,
    DEP.NUMBER_OF_PATIENTS
FROM DOCTOR D
    LEFT JOIN SPECIALITY SP ON D.SPCLTY_ID = SP.ID
    LEFT JOIN CABINET C ON D.CAB_ID = C.ID
    LEFT JOIN DEPARTMENT DEP ON D.DEP_ID = DEP.ID
HAVING DEP.NUMBER_OF_PATIENTS > 4;

SELECT 
    P.FIRST_NAME, 
    P.LAST_NAME, 
    P.AGE, 
    P.PERS_CODE, 
    P.ADDRESS.
    P.FEE
FROM PATIENT P
    ORDER BY P.FIRST_NAME;
    
SELECT 
    D.FIRST_NAME, 
    D.LAST_NAME, 
    MAX(C.NUMBER_OF_PERS)
FROM DOCTOR D
    LEFT JOIN CABINET C ON D.CAB_ID = C.ID
GROUP BY D.FIRST_NAME, 
        D.LAST_NAME;

SELECT DISTINCT 
    D.FIRST_NAME, 
    D.LAST_NAME, 
    D.POSITION, 
    D.EXPERIENCE_YEARS,
    SP.SPEC_NAME,
    SP.EXP_REQUIRED,
    C.ROOM_NUMBER,
    C.ROOM_TITLE,
    C.NUMBER_OF_PERS,
    DEP.TITLE,
    DEP.NUMBER_OF_PATIENTS
FROM DOCTOR D
    LEFT JOIN SPECIALITY SP ON D.SPCLTY_ID = SP.ID
    LEFT JOIN CABINET C ON D.CAB_ID = C.ID
    LEFT JOIN DEPARTMENT DEP ON D.DEP_ID = DEP.ID;
    
SELECT 
    D.FIRST_NAME, 
    D.LAST_NAME, 
    D.POSITION, 
    SP.SPEC_NAME,
    (D.EXPERIENCE_YEARS + SP.EXP_REQUIRED) as FULL_EXP,
    C.ROOM_NUMBER,
    C.ROOM_TITLE,
    C.NUMBER_OF_PERS,
    DEP.TITLE,
    DEP.NUMBER_OF_PATIENTS
FROM DOCTOR D
    LEFT JOIN SPECIALITY SP ON D.SPCLTY_ID = SP.ID
    LEFT JOIN CABINET C ON D.CAB_ID = C.ID
    LEFT JOIN DEPARTMENT DEP ON D.DEP_ID = DEP.ID;

SELECT 
    D.FIRST_NAME, 
    D.LAST_NAME, 
    D.POSITION, 
    D.EXPERIENCE_YEARS,
    SP.SPEC_NAME,
    SP.EXP_REQUIRED,
    C.ROOM_NUMBER,
    C.ROOM_TITLE,
    C.NUMBER_OF_PERS,
    DEP.TITLE,
    DEP.NUMBER_OF_PATIENTS
FROM DOCTOR D
    RIGHT JOIN SPECIALITY SP ON D.SPCLTY_ID = SP.ID
    RIGHT JOIN CABINET C ON D.CAB_ID = C.ID
    RIGHT JOIN DEPARTMENT DEP ON D.DEP_ID = DEP.ID;
    
SELECT * FROM DOCTOR WHERE ID = 1;
UPDATE DOCTOR D SET EXPERIENCE_YEARS = 2 WHERE ID = 1;
SELECT * FROM DOCTOR WHERE ID = 1;

(SELECT
    D.FIRST_NAME as d_first_name, 
    D.LAST_NAME as d_last_name 
FROM DOCTOR D)
UNION
(SELECT
    p.first_name as p_first_name,
    p.last_name as p_last_name
FROM patient p);

select * from doctor;
select * from speciality;

SELECT 
    D.FIRST_NAME,
    D.LAST_NAME,
    D.POSITION,
    SP.SPEC_NAME,
    SP.EXP_REQUIRED
FROM DOCTOR D
FULL OUTER JOIN SPECIALITY SP
ON D.SPCLTY_ID = SP.ID;
        
SELECT 
    P.FIRST_NAME,
    P.LAST_NAME
FROM PATIENT P
WHERE FIRST_NAME LIKE 'C%';

SELECT 
    D.FIRST_NAME,
    D.LAST_NAME
FROM DOCTOR D
WHERE DEP_ID IN (
    SELECT ID FROM DEPARTMENT DEP WHERE D.DEP_ID = DEP.ID
);

SELECT
    FIRST_NAME,
    LAST_NAME
FROM (
    SELECT 
        D.FIRST_NAME,
        D.LAST_NAME,
        DEP.TITLE, 
        DEP.WORKERS_QUANTITY, 
        DEP.NUMBER_OF_PATIENTS
    FROM DOCTOR D
    LEFT JOIN DEPARTMENT DEP 
        ON D.DEP_ID = D.ID
);

select * from doctor;

SELECT 
    D.FIRST_NAME,
    D.LAST_NAME,
    AVG(D.EXPERIENCE_YEARS) AS AVG_EXP
FROM DOCTOR D
WHERE 
    D.POSITION = 'Dermatologist'
GROUP BY
    D.FIRST_NAME,
    D.LAST_NAME,
    D.EXPERIENCE_YEARS
HAVING AVG(EXPERIENCE_YEARS) > 5;

SELECT 
    D.FIRST_NAME,
    D.LAST_NAME,
    D.AGE,
    DEP.TITLE,
    DEP.WORKERS_QUANTITY,
    DEP.NUMBER_OF_PATIENTS
FROM DOCTOR D
CROSS JOIN DEPARTMENT DEP;

select 
    d.first_name,
    dep.title as dep_title
from 
    doctor d, 
    department dep
where d.dep_id = dep.id
group by d.id
having count(dep.number_of_patients) >=
    (select count(dep.number_of_patients)
        from doctor d, department dep
        where d.dep_id = dep.id group by dep.id);